apiVersion: v1
kind: Namespace
metadata:
  name: openairinterface
  labels:
    nephio.org/cluster-name: example-cluster # kpt-set: ${cluster-name}
---
apiVersion: v1
kind: Namespace
metadata:
  name: free5gc
  labels:
    nephio.org/cluster-name: example-cluster # kpt-set: ${cluster-name}
